# Generated by Django 3.1.2 on 2021-10-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('costumerid', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=100)),
                ('lastupdateuser', models.CharField(max_length=50)),
                ('createuser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=20)),
                ('adminstatus', models.CharField(max_length=20)),
            ],
        ),
    ]
