# Generated by Django 3.1.2 on 2021-10-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersAPP', '0003_auto_20210930_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='lastupdateuser',
            field=models.CharField(max_length=50),
        ),
    ]
