# Generated by Django 3.1.2 on 2021-10-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersAPP', '0005_auto_20210930_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='photo',
            field=models.ImageField(null=True, upload_to='customersAPP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='adminstatus',
            field=models.BooleanField(default=False),
        ),
    ]
