# Generated by Django 3.1.2 on 2021-10-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customersAPP', '0012_auto_20211001_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='creatoruser_id',
        ),
        migrations.AddField(
            model_name='costumer',
            name='creatoruser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='lastupdateuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lastupdateuser', to='customersAPP.user'),
        ),
    ]
