# Generated by Django 3.1.2 on 2021-10-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersAPP', '0013_auto_20211003_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
