# Generated by Django 3.1.2 on 2021-10-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customersAPP', '0014_auto_20211003_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='lastupdateuser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
