# Generated by Django 3.1.2 on 2021-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersAPP', '0015_auto_20211004_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='photo',
            field=models.ImageField(null=True, upload_to='customersAPP'),
        ),
    ]
