# Generated by Django 3.1.2 on 2021-10-07 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customersAPP', '0018_costumer_lastupdateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='creatoruser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatoruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='lastupdateuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastupdateuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
